name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Build and Test
      run: |
        ./mvnw clean install

    - name: Build Docker Image
      run: |
        docker build -t github-action-cicd:1.0 -f .
      working-directory: ${{ github.workspace }}

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image
      run: |
        docker tag github-action-cicd:1.0 ${{ secrets.DOCKER_USERNAME }}/github-action-cicd:1.0
        docker push ${{ secrets.DOCKER_USERNAME }}/github-action-cicd:1.0

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Docker Hub
      run: echo "Deployment to Docker Hub complete"
